server:
  port: 8083

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user/**
          filters:
            - name: RequestLoggingGatewayFilterFactory
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/order/**
          filters:
            - name: RequestLoggingGatewayFilterFactory

logging:
  level:
    org.springframework.cloud.gateway: DEBUG